# Example 4 - Using JS action
name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  get-gitlab-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Using action a 
        uses: actions/checkout@v4
        with:
          repository: 'my-group/node-website'
          url: 'https://gitlab.com/eduardojavier.lv/cars-api.git'
          ref: 'master'
          token: 'glpat-ykUr4y_iacN2YLJytdzs'