# Example 4 - Using JS action
name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  get-gitlab-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Using action a 
        uses: actions/checkout@v4
        with:
          repository: 'my-group4174747/node-website'
          ref: 'main'
          token: 'glpat-ykUr4y_iacN2YLJytdzs'
          github-server-url: 'https://gitlab.com'