# Example 4 - Using JS action
name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  get-gitlab-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning gitlab repo 
        uses: actions/checkout@v4
        with:
          repository: 'prodeng-cloud/stuffstore'
          ref: 'master'
          token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          github-server-url: 'https://atom-git.turner.com'
      - name: See all the repo file
        run: |
          ls -l

      # - name: Using action a 
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'my-group4174747/node-website'
      #     ref: 'main'
      #     token: 'glpat-ykUr4y_iacN2YLJytdzs'
      #     github-server-url: 'https://gitlab.com'
      # - name: See all the repo file
      #   run: |
      #     ls -l